secretGenerator:
  - name: repository-pat
  - name: mongodb-auth
    type: Opaque
    envs:
      - params/mongodb-auth.env
    options:
     disableNameSuffixHash: true
  - name: oidc-client
    type: Opaque
    envs:
      - params/oidc-client.env
    options:
        disableNameSuffixHash: true