apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: cv1pb-ambulance-ufe-content
spec:
  microFrontend: cv1pb-ambulance-ufe
  element: cv1pb-ambulance-wl-app
  attributes:
    - name: api-base
      value: http://localhost:5000/api
    - name: ambulance-id
      value: bobulova
    - name: base-path
      value: /cv1pb-ambulance-wl/
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?cv1pb-ambulance-wl(/.*)?$"