apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: cv1pb-ambulance-ufe-content
spec:
  microFrontend: cv1pb-ambulance-ufe
  element: cv1pb-ambulance-wl-list
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?cv1pb-ambulance-wl(/.*)?$"